NNP STM Bootloader: Core/Src/main.c File Reference
main.c File Reference
: Main program body
#include "main.h"
#include "can_protocol.h"
#include "stm32l4xx_hal_flash_ex.h"
#include "config.h"
Functions
void SystemClock_Config (void)
System Clock Configuration.
uint8_t enableWRP ()
Enables write protection over bootloader.
int main (void)
The application entry point.
void Error_Handler (void)
This function is executed in case of error occurrence.
Variables
FLASH_OBProgramInitTypeDef flashOB = {0}
Flash option bytes for setting write protection.
CAN_HandleTypeDef hcan1
CAN_TxHeaderTypeDef TxHeader
CAN_RxHeaderTypeDef RxHeader
uint8_t TxData [8]
uint8_t RxData [8]
uint32_t TxMailbox
uint16_t offset_id_copy
Working copy of offset ID.
char nnb_copy
Working copy of Node ID.
char f_communication_open
0 = Closed, 1 = Open and Unique
char f_frame_to_send
uint32_t nb_byte_to_write = 0
uint32_t nb_byte_to_read = 0
uint32_t pagenum
uint32_t pt_buffer
uint32_t start_address = 0x08000000
uint32_t address = 0x08000000
uint32_t end_address = 0x08000000
uint16_t chksum = 0
uint32_t sizeApp
char buffer [64] = {0}
Detailed Description
: Main program body
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file main.c.
Function Documentation
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 349 of file main.c.
Referenced by can_display_data(), HAL_CAN_ErrorCallback(), HAL_CAN_RxFifo0MsgPendingCallback(), JumpToApplication(), and SystemClock_Config().
main()
int main (void)
The application entry point.
Return values
int
Definition at line 145 of file main.c.
SystemClock_Config()
void SystemClock_Config (void)
System Clock Configuration.
Return values
None
Configure the main internal regulator output voltage
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure.
Initializes the CPU, AHB and APB buses clocks
Definition at line 200 of file main.c.
Referenced by main().
Variable Documentation
address
uint32_t address = 0x08000000
Definition at line 72 of file main.c.
buffer
char buffer[64] = {0}
Definition at line 78 of file main.c.
chksum
uint16_t chksum = 0
Definition at line 75 of file main.c.
end_address
uint32_t end_address = 0x08000000
Definition at line 73 of file main.c.
f_communication_open
char f_communication_open
0 = Closed, 1 = Open and Unique
Definition at line 62 of file main.c.
Referenced by HAL_CAN_RxFifo0MsgPendingCallback().
f_frame_to_send
char f_frame_to_send
Definition at line 63 of file main.c.
flashOB
FLASH_OBProgramInitTypeDef flashOB = {0}
Flash option bytes for setting write protection.
Definition at line 50 of file main.c.
Referenced by enableWRP().
hcan1
CAN_HandleTypeDef hcan1
Definition at line 51 of file main.c.
nb_byte_to_read
uint32_t nb_byte_to_read = 0
Definition at line 66 of file main.c.
nb_byte_to_write
uint32_t nb_byte_to_write = 0
Definition at line 65 of file main.c.
nnb_copy
char nnb_copy
Working copy of Node ID.
Definition at line 60 of file main.c.
Referenced by HAL_CAN_RxFifo0MsgPendingCallback().
offset_id_copy
uint16_t offset_id_copy
Working copy of offset ID.
Definition at line 59 of file main.c.
Referenced by HAL_CAN_RxFifo0MsgPendingCallback(), and send_error_security().
pagenum
uint32_t pagenum
Definition at line 68 of file main.c.
pt_buffer
uint32_t pt_buffer
Definition at line 69 of file main.c.
RxData
uint8_t RxData[8]
Definition at line 56 of file main.c.
RxHeader
CAN_RxHeaderTypeDef RxHeader
Definition at line 54 of file main.c.
sizeApp
uint32_t sizeApp
Definition at line 76 of file main.c.
start_address
uint32_t start_address = 0x08000000
Definition at line 71 of file main.c.
TxData
uint8_t TxData[8]
Definition at line 55 of file main.c.
TxHeader
CAN_TxHeaderTypeDef TxHeader
Definition at line 53 of file main.c.
TxMailbox
uint32_t TxMailbox
Definition at line 57 of file main.c.