NNP STM Bootloader: FESCAN
FESCAN
Functions
void send_error_security (void)
Configure CAN message to send when SELECT_MEM_PAGE is used.
void HAL_CAN_ErrorCallback (CAN_HandleTypeDef *hcan)
CAN message callback that handles errors with communication.
void HAL_CAN_RxFifo0MsgPendingCallback (CAN_HandleTypeDef *hcan)
CAN message callback that handles communication with the network.
Detailed Description
Function Documentation
HAL_CAN_ErrorCallback()
void HAL_CAN_ErrorCallback (CAN_HandleTypeDef * hcan)
CAN message callback that handles errors with communication.
Definition at line 328 of file can_protocol.c.
HAL_CAN_RxFifo0MsgPendingCallback()
void HAL_CAN_RxFifo0MsgPendingCallback (CAN_HandleTypeDef * hcan)
CAN message callback that handles communication with the network.
Definition at line 337 of file can_protocol.c.
send_error_security()
void send_error_security (void)
Configure CAN message to send when SELECT_MEM_PAGE is used.
Definition at line 64 of file can_protocol.c.
Referenced by can_display_data(), can_init_write_data(), and HAL_CAN_RxFifo0MsgPendingCallback().