NNP STM Bootloader: Bootloader
Bootloader
Files
file config.h
Configures memory spaces and other boot settings.
Classes
union convertParam
Structure to convert raw data to parameter set.
union Union32
Union structure to convert between words, half words, and quarter words.
Functions
void can_init_display_data (void)
Initializes global address range from received CAN message in preparation for can_display_data.
void can_init_write_data (void)
Initializes global address range from received CAN message in preparation for can_write_data.
void can_display_data (void)
Displays requested data over the CAN network.
char can_write_data (void)
Copy data to write to flash into a buffer (max of 64 bytes). When nb_byte_to_write reaches 0, commit data to flash.
uint32_t blank_flash_check (uint32_t start, uint32_t end)
Checks for first blank location of flash between two addresses, and returns that location, otherwise, return 0.
uint8_t calc_app_checksum (uint32_t size)
Calculates a checksum across application code.
volatile void JumpToApplication ()
Transfer control of microcontroller to user application after deinitializing peripherals and moving relevant pointers.
uint8_t enableWRP ()
Enables write protection over bootloader.
Variables
union Union32 u32
Detailed Description
Function Documentation
blank_flash_check()
uint32_t blank_flash_check (uint32_t start, uint32_t end)
Checks for first blank location of flash between two addresses, and returns that location, otherwise, return 0.
Parameters
start start address
end end address
Return values
uint32_t Address of first non-empty location, 0 if none
Definition at line 226 of file can_protocol.c.
Referenced by HAL_CAN_RxFifo0MsgPendingCallback().
calc_app_checksum()
uint8_t calc_app_checksum (uint32_t size)
Calculates a checksum across application code.
Parameters
size length of application code to sum over
Return values
uint8_t Checksum
Definition at line 243 of file can_protocol.c.
Referenced by HAL_CAN_RxFifo0MsgPendingCallback(), and JumpToApplication().
can_display_data()
void can_display_data (void)
Displays requested data over the CAN network.
Definition at line 113 of file can_protocol.c.
Referenced by HAL_CAN_RxFifo0MsgPendingCallback().
can_init_display_data()
void can_init_display_data (void)
Initializes global address range from received CAN message in preparation for can_display_data.
Definition at line 77 of file can_protocol.c.
Referenced by HAL_CAN_RxFifo0MsgPendingCallback().
can_init_write_data()
void can_init_write_data (void)
Initializes global address range from received CAN message in preparation for can_write_data.
Definition at line 92 of file can_protocol.c.
Referenced by HAL_CAN_RxFifo0MsgPendingCallback().
can_write_data()
char can_write_data (void)
Copy data to write to flash into a buffer (max of 64 bytes). When nb_byte_to_write reaches 0, commit data to flash.
Return values
char Response to CAN network
Definition at line 171 of file can_protocol.c.
Referenced by HAL_CAN_RxFifo0MsgPendingCallback().
enableWRP()
uint8_t enableWRP ()
Enables write protection over bootloader.
Return values
uint8_t success
Definition at line 98 of file main.c.
Referenced by main().
JumpToApplication()
volatile void JumpToApplication ()
Transfer control of microcontroller to user application after deinitializing peripherals and moving relevant pointers.
Note
If APP_SIZE is defined in the parameter space, and the checksum matches what is calculated, then the application starts, otherwise if size is 0 or greater than MAX_APP_SIZE, the check is overridden.
As per AN2606, CAN interface may not work correctly if RTC is not reset in application prior to loading bootloader, else a power cycle is required.
Definition at line 268 of file can_protocol.c.
Referenced by main().